test:
  image: phusion/baseimage
  command: bash -c "apt-get update"

packetbeat:
  build: .
  container_name: packetbeat
  command: >
    /bin/bash -c "
        echo Waiting for Kibana to become ready ...
        while ! curl -s http://localhost:5601 &>/dev/null; do sleep 3;done;
        echo Kibana is ready : http://localhost:5601
        echo Starting Packetbeat : ./packetbeat -e -c=packetbeat.yml
        ./packetbeat -e -c=packetbeat.yml
    "
  net: "host"
  links:
   - kibana 

kibana:
  image: kibana:latest
  container_name: kibana
  ports:
   - "5601:5601"
  environment:
   - ELASTICSEARCH_URL=http://elasticsearch:9200
  links:
   - elasticsearch

elasticsearch:
  container_name: elasticsearch
  image: elasticsearch:latest
  ports:
   - "9200:9200"
   - "9300:9300"

